// AUTO-GENERATED by scripts/gen-proto.ts from proto/clipboard.v1.schema.json.
// Do not edit by hand. Run `bun run gen:proto` to regenerate.

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const BASE64_RE = /^[A-Za-z0-9+/]*={0,2}$/;

export interface SessionCreate {
  kind: "session.create";
  code: string;
  version?: string;
}

export interface SessionJoin {
  kind: "session.join";
  code: string;
  version?: string;
}

export interface SessionLeave {
  kind: "session.leave";
  code: string;
}

export interface SdpOffer {
  kind: "sdp.offer";
  type: "offer";
  sdp: string;
}

export interface SdpAnswer {
  kind: "sdp.answer";
  type: "answer";
  sdp: string;
}

export interface IceCandidate {
  kind: "ice.candidate";
  candidate: string;
  sdpMid: string | null;
  sdpMLineIndex: number | null;
}

export interface RelayChunk {
  kind: "relay.chunk";
  transferId: string;
  seq: number;
  total: number;
  bytes: string;
  meta?: ChunkMeta;
}

export interface RelayAck {
  kind: "relay.ack";
  transferId: string;
  seq: number;
}

export interface RelayCancel {
  kind: "relay.cancel";
  transferId: string;
  reason: string;
}

export interface RelayResume {
  kind: "relay.resume";
  transferId: string;
  fromSeq: number;
}

export interface RelayError {
  kind: "relay.error";
  transferId?: string;
  code: "over-cap" | "room-full" | "room-limit" | "rate-limited" | "expired" | "internal";
  message: string;
}

export interface RelayComplete {
  kind: "relay.complete";
  transferId: string;
}

export interface DcChunk {
  kind: "dc.chunk";
  transferId: string;
  seq: number;
  total: number;
  bytes: string;
  meta?: ChunkMeta;
}

export interface DcAck {
  kind: "dc.ack";
  transferId: string;
  seq: number;
}

export interface DcCancel {
  kind: "dc.cancel";
  transferId: string;
  reason: string;
}

export interface DcResume {
  kind: "dc.resume";
  transferId: string;
  fromSeq: number;
}

export interface DcError {
  kind: "dc.error";
  transferId?: string;
  code: "over-cap" | "room-full" | "room-limit" | "rate-limited" | "expired" | "internal";
  message: string;
}

export interface ChunkMeta {
  mime: string;
  name: string;
  size: number;
}

export type ClipboardMessage =
  | SessionCreate
  | SessionJoin
  | SessionLeave
  | SdpOffer
  | SdpAnswer
  | IceCandidate
  | RelayChunk
  | RelayAck
  | RelayCancel
  | RelayResume
  | RelayError
  | RelayComplete
  | DcChunk
  | DcAck
  | DcCancel
  | DcResume
  | DcError;

function isSessionCreate(x: unknown): x is SessionCreate {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "session.create") return false;
  if (typeof o.code !== "string") return false;
  if (o.version !== undefined && typeof o.version !== "string") return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "code", "version"].includes(k)) return false;
  }
  return true;
}

function isSessionJoin(x: unknown): x is SessionJoin {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "session.join") return false;
  if (typeof o.code !== "string") return false;
  if (o.version !== undefined && typeof o.version !== "string") return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "code", "version"].includes(k)) return false;
  }
  return true;
}

function isSessionLeave(x: unknown): x is SessionLeave {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "session.leave") return false;
  if (typeof o.code !== "string") return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "code"].includes(k)) return false;
  }
  return true;
}

function isSdpOffer(x: unknown): x is SdpOffer {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "sdp.offer") return false;
  if (o.type !== "offer") return false;
  if (typeof o.sdp !== "string") return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "type", "sdp"].includes(k)) return false;
  }
  return true;
}

function isSdpAnswer(x: unknown): x is SdpAnswer {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "sdp.answer") return false;
  if (o.type !== "answer") return false;
  if (typeof o.sdp !== "string") return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "type", "sdp"].includes(k)) return false;
  }
  return true;
}

function isIceCandidate(x: unknown): x is IceCandidate {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "ice.candidate") return false;
  if (typeof o.candidate !== "string") return false;
  if (o.sdpMid !== null && typeof o.sdpMid !== "string") return false;
  if (o.sdpMLineIndex !== null && typeof o.sdpMLineIndex !== "number") return false;
  if (o.sdpMLineIndex !== null && !Number.isInteger(o.sdpMLineIndex)) return false;
  if (o.sdpMLineIndex !== null && o.sdpMLineIndex < 0) return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "candidate", "sdpMid", "sdpMLineIndex"].includes(k)) return false;
  }
  return true;
}

function isRelayChunk(x: unknown): x is RelayChunk {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "relay.chunk") return false;
  if (typeof o.transferId !== "string") return false;
  if (!UUID_RE.test(o.transferId)) return false;
  if (typeof o.seq !== "number") return false;
  if (!Number.isInteger(o.seq)) return false;
  if (o.seq < 0) return false;
  if (typeof o.total !== "number") return false;
  if (!Number.isInteger(o.total)) return false;
  if (o.total < 1) return false;
  if (typeof o.bytes !== "string") return false;
  if (!BASE64_RE.test(o.bytes)) return false;
  if (o.meta !== undefined && !isChunkMeta(o.meta)) return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "transferId", "seq", "total", "bytes", "meta"].includes(k)) return false;
  }
  return true;
}

function isRelayAck(x: unknown): x is RelayAck {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "relay.ack") return false;
  if (typeof o.transferId !== "string") return false;
  if (!UUID_RE.test(o.transferId)) return false;
  if (typeof o.seq !== "number") return false;
  if (!Number.isInteger(o.seq)) return false;
  if (o.seq < 0) return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "transferId", "seq"].includes(k)) return false;
  }
  return true;
}

function isRelayCancel(x: unknown): x is RelayCancel {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "relay.cancel") return false;
  if (typeof o.transferId !== "string") return false;
  if (!UUID_RE.test(o.transferId)) return false;
  if (typeof o.reason !== "string") return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "transferId", "reason"].includes(k)) return false;
  }
  return true;
}

function isRelayResume(x: unknown): x is RelayResume {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "relay.resume") return false;
  if (typeof o.transferId !== "string") return false;
  if (!UUID_RE.test(o.transferId)) return false;
  if (typeof o.fromSeq !== "number") return false;
  if (!Number.isInteger(o.fromSeq)) return false;
  if (o.fromSeq < 0) return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "transferId", "fromSeq"].includes(k)) return false;
  }
  return true;
}

function isRelayError(x: unknown): x is RelayError {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "relay.error") return false;
  if (o.transferId !== undefined && typeof o.transferId !== "string") return false;
  if (o.transferId !== undefined && !UUID_RE.test(o.transferId)) return false;
  if (
    !["over-cap", "room-full", "room-limit", "rate-limited", "expired", "internal"].some(
      (v) => v === o.code,
    )
  )
    return false;
  if (typeof o.message !== "string") return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "transferId", "code", "message"].includes(k)) return false;
  }
  return true;
}

function isRelayComplete(x: unknown): x is RelayComplete {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "relay.complete") return false;
  if (typeof o.transferId !== "string") return false;
  if (!UUID_RE.test(o.transferId)) return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "transferId"].includes(k)) return false;
  }
  return true;
}

function isDcChunk(x: unknown): x is DcChunk {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "dc.chunk") return false;
  if (typeof o.transferId !== "string") return false;
  if (!UUID_RE.test(o.transferId)) return false;
  if (typeof o.seq !== "number") return false;
  if (!Number.isInteger(o.seq)) return false;
  if (o.seq < 0) return false;
  if (typeof o.total !== "number") return false;
  if (!Number.isInteger(o.total)) return false;
  if (o.total < 1) return false;
  if (typeof o.bytes !== "string") return false;
  if (!BASE64_RE.test(o.bytes)) return false;
  if (o.meta !== undefined && !isChunkMeta(o.meta)) return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "transferId", "seq", "total", "bytes", "meta"].includes(k)) return false;
  }
  return true;
}

function isDcAck(x: unknown): x is DcAck {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "dc.ack") return false;
  if (typeof o.transferId !== "string") return false;
  if (!UUID_RE.test(o.transferId)) return false;
  if (typeof o.seq !== "number") return false;
  if (!Number.isInteger(o.seq)) return false;
  if (o.seq < 0) return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "transferId", "seq"].includes(k)) return false;
  }
  return true;
}

function isDcCancel(x: unknown): x is DcCancel {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "dc.cancel") return false;
  if (typeof o.transferId !== "string") return false;
  if (!UUID_RE.test(o.transferId)) return false;
  if (typeof o.reason !== "string") return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "transferId", "reason"].includes(k)) return false;
  }
  return true;
}

function isDcResume(x: unknown): x is DcResume {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "dc.resume") return false;
  if (typeof o.transferId !== "string") return false;
  if (!UUID_RE.test(o.transferId)) return false;
  if (typeof o.fromSeq !== "number") return false;
  if (!Number.isInteger(o.fromSeq)) return false;
  if (o.fromSeq < 0) return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "transferId", "fromSeq"].includes(k)) return false;
  }
  return true;
}

function isDcError(x: unknown): x is DcError {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.kind !== "dc.error") return false;
  if (o.transferId !== undefined && typeof o.transferId !== "string") return false;
  if (o.transferId !== undefined && !UUID_RE.test(o.transferId)) return false;
  if (
    !["over-cap", "room-full", "room-limit", "rate-limited", "expired", "internal"].some(
      (v) => v === o.code,
    )
  )
    return false;
  if (typeof o.message !== "string") return false;
  for (const k of Object.keys(o)) {
    if (!["kind", "transferId", "code", "message"].includes(k)) return false;
  }
  return true;
}

function isChunkMeta(x: unknown): x is ChunkMeta {
  if (typeof x !== "object" || x === null) return false;
  const o = x as Record<string, unknown>;
  if (typeof o.mime !== "string") return false;
  if (typeof o.name !== "string") return false;
  if (typeof o.size !== "number") return false;
  if (!Number.isInteger(o.size)) return false;
  if (o.size < 0) return false;
  for (const k of Object.keys(o)) {
    if (!["mime", "name", "size"].includes(k)) return false;
  }
  return true;
}

export function parseMessage(input: unknown): ClipboardMessage | null {
  if (typeof input !== "object" || input === null) return null;
  const o = input as Record<string, unknown>;
  if (typeof o.kind !== "string") return null;
  switch (o.kind) {
    case "session.create":
      return isSessionCreate(input) ? input : null;
    case "session.join":
      return isSessionJoin(input) ? input : null;
    case "session.leave":
      return isSessionLeave(input) ? input : null;
    case "sdp.offer":
      return isSdpOffer(input) ? input : null;
    case "sdp.answer":
      return isSdpAnswer(input) ? input : null;
    case "ice.candidate":
      return isIceCandidate(input) ? input : null;
    case "relay.chunk":
      return isRelayChunk(input) ? input : null;
    case "relay.ack":
      return isRelayAck(input) ? input : null;
    case "relay.cancel":
      return isRelayCancel(input) ? input : null;
    case "relay.resume":
      return isRelayResume(input) ? input : null;
    case "relay.error":
      return isRelayError(input) ? input : null;
    case "relay.complete":
      return isRelayComplete(input) ? input : null;
    case "dc.chunk":
      return isDcChunk(input) ? input : null;
    case "dc.ack":
      return isDcAck(input) ? input : null;
    case "dc.cancel":
      return isDcCancel(input) ? input : null;
    case "dc.resume":
      return isDcResume(input) ? input : null;
    case "dc.error":
      return isDcError(input) ? input : null;
    default:
      return null;
  }
}
